Include lofreq module, and merge lofreq and ivar results
nf-core/viralrecon pull request #432
Opened 2024-06-11 07:41 UTC by shesanIsland

# nf-core/viralrecon pull request

2024-06-13 14:03 UTC, Joon-Klaps requested changes
Resolve the merge conflicts, then the CI testing, will help you clarify a couple of the bugs. Let me know if you need any help with this.

2024-06-13 14:03 UTC, Joon-Klaps commented on conf/modules_illumina.config
> +            withName: 'VARIANTS_IVAR:IVAR_VARIANTS' {
```suggestion
            withName: 'IVAR_VARIANTS' {
```

2024-06-13 14:03 UTC, Joon-Klaps commented on workflows/illumina.nf
> +    variant_callers   : ['ivar', 'bcftools'. 'lofreq'],
update parameter schema `nf-core schema build` as wel

2024-06-13 14:03 UTC, Joon-Klaps commented on workflows/illumina.nf
>  include { CUSTOM_DUMPSOFTWAREVERSIONS   } from '../modules/nf-core/custom/dumpsoftwareversions/main'
```suggestion
include { CUSTOM_DUMPSOFTWAREVERSIONS   } from '../modules/nf-core/custom/dumpsoftwareversions/main'
```
No need to call modules in the main workflow if they are not used in that workflow. You already call them in the `LOFREQ_IVAR` subworkflow.

2024-06-13 14:03 UTC, Joon-Klaps commented on workflows/illumina.nf
> +
Think you forgot to refactor this by calling the subworkflow

2024-06-13 14:03 UTC, Joon-Klaps commented on subworkflows/local/lofreq_ivar.nf
> +
Only call what you need.

2026-01-22 09:58 UTC, LilyAnderssonLee commented
@shesanIsland Can you still work on this issue? I can take over if you can't find time to work on this before March.

2026-01-26 12:48 UTC, shesanIsland commented
> @shesanIsland Can you still work on this issue? I can take over if you can't find time to work on this before March.

Unfortunately I won't be able to revisit this anytime soon so it will need to be handed over. Apologies.

2026-03-05 18:58 UTC, lpantano commented
Hi, I am closing this PR since is too old. Feel free to reopen with updated code to get the tests passing. Sorry we didn't get to merge on time.

2026-03-05 18:58 UTC, closed without merging