Changed Cutadapt to use nf-core modules
nf-core/viralrecon pull request #435
Opened 2024-06-18 10:18 UTC by svarona

Fixes issue #409 

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/viralrecon/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/viralrecon _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`).
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [X] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [X] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-20 08:05 UTC, maxulysse approved these changes

2024-10-07 18:15 UTC, maxulysse commented on CHANGELOG.md
> +| `cutadapt` |             | 4.6         |
```suggestion
```

Duplicate

2024-10-07 18:15 UTC, maxulysse approved these changes

2024-10-17 13:51 UTC, maxulysse commented
So the issue there is that we no longer have the adapter file in the script and we're trying to pass it within the meta map.
We should only pass files to modules within a channel.
I'd recommend to patch the modules upstream and keep this adapter input

2024-10-18 16:16 UTC, maxulysse commented on conf/modules_illumina.config
> +                    "${meta.single_end}" == true ? "-g file:${meta.primers}" : "-g file:${meta.primers} -G file:${meta.primers}"
we cannot pass files here

2024-10-18 16:17 UTC, maxulysse requested changes
We should only pass files to modules within a channel.
I'd recommend to patch the modules upstream and keep this adapter input in cutadapt

2024-10-25 14:31 UTC, svarona commented
> We should only pass files to modules within a channel. I'd recommend to patch the modules upstream and keep this adapter input in cutadapt

Thanks a lot @maxulysse! Just learned about this patch thing thanks to having @Daniel-VM nearby at work! I'm already working on it!!

2024-10-25 16:23 UTC, maxulysse approved these changes

2024-10-25 16:23 UTC, merged